/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.tom65536.tingle;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class TingleGradlePlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("tangle", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'io.github.tom65536.tingle'"));
        });
    }
}
